### ISSUE TITLE
Possible bug with Schedulers

### ISSUE THREAD

**Issue by pennyvc** [BlenderNeko/ComfyUI_Cutoff#16]
Was making a tutorial video/learning how to use the node and stumbled into a bug that was getting in the way of this working correctly.
Cutoff seemed to get overwhelmed by the 'Karras" Scheduler, seems like this re-sets the clip or re-runs it without the cutoff component.

https://youtu.be/ZZ1bc5T094s?t=1048   its a long vid but this is where I noticed a rather obvious seeming change in the sampler behaviour.

**Comment by BlenderNeko** [comment]
The cutoff nodes have absolutely no idea what scheduler you pick because this happens later in the pipeline. Likewise, the sampler has no influence on what happens in the cutoff nodes, it simply receives the calculated clip embeddings and that's it. As for the video snipped: all the scheduler dictates is how much noise should be removed each step, it's the sampler that decided how to go about this and ancestral samplers are the ones that take two attempts for every step to hopefully get a better noise prediction.

It could be that cutoff is less effective in conjunction with a karas noise schedule because that schedule spends less time in the early stages of denoising, where the composition of the image is formed. It could be that the given model is less receptive to what cutoff does, or maybe you're just having bad luck.

**Comment by pennyvc** [comment]
All good, Ill mark this closed then if you reckon its not a bug. It was definitely trying to do what was asked but yeah, seemed to be getting overridden in the denoising process for some reason.

I ran it a couple of hundred times after the vid, was a fairly obvious distinction with and without karas. but yeah, normal works so ill use that :D
